### ISSUE TITLE
Code Integrety Check failed

### ISSUE THREAD

**Issue by gjelsas** [pbek/ownbackup#10]
Results
=======
- ownbackup
	- INVALID_HASH
		- README.md
		- appinfo/info.xml

Raw output
==========
Array
(
    [ownbackup] => Array
        (
            [INVALID_HASH] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
                            [current] => 19292ca3fd349cb446ad6f374ab62b4b9e0f8f69c863460e53a36271c14f59fa64bc783979edbf084b423c44c3fd3860e09814320ad7f2ab6558e4b9b459bf0f
                        )

                    [appinfo/info.xml] => Array
                        (
                            [expected] => 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
                            [current] => 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add
                        )

                )

        )

)

I'm on Nextcloud 11.0 and owmnbackup from the appstore.

**Comment by gjelsas** [comment]
Sorry ,
works with the github version...

**Comment by pbek** [comment]
...and probably the NC store version. ;)

**Comment by gjelsas** [comment]
'Think I closed it prematurely!

This is with the github version:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- ownbackup
	- FILE_MISSING
		- .editorconfig
	- INVALID_HASH
		- README.md
		- appinfo/info.xml
	- EXTRA_FILE
		- .git/objects/pack/pack-112ea9a83fa76468c74ce0f7b4703fe0ad289540.pack
		- .git/objects/pack/pack-112ea9a83fa76468c74ce0f7b4703fe0ad289540.idx
		- .git/info/exclude
		- .git/HEAD
		- .git/description
		- .git/hooks/commit-msg.sample
		- .git/hooks/applypatch-msg.sample
		- .git/hooks/pre-push.sample
		- .git/hooks/prepare-commit-msg.sample
		- .git/hooks/post-update.sample
		- .git/hooks/pre-rebase.sample
		- .git/hooks/pre-commit.sample
		- .git/hooks/pre-applypatch.sample
		- .git/hooks/update.sample
		- .git/config
		- .git/index
		- .git/refs/heads/develop
		- .git/refs/remotes/origin/HEAD
		- .git/logs/HEAD
		- .git/packed-refs

Raw output
==========
Array
(
    [ownbackup] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.editorconfig] => Array
                        (
                            [expected] => 3f6603e83dd948fb07946fd9fee11673c1196a3e3710a6b5dfd2f8861a3cfd49a8abca1273f9678f529d0c2edca9fd3f6d51adc07bcd071f9aa0716075f7e048
                            [current] => 
                        )

                )

            [INVALID_HASH] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
                            [current] => ece1addb7b7eda683984d18641b06a7c19e464954859b32fced97d2b5006b9a7bc3e2bdaa57194a635155ba0104750eb7f495a383a0bdcc609a00147cc5cb6f5
                        )

                    [appinfo/info.xml] => Array
                        (
                            [expected] => 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
                            [current] => 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.git/objects/pack/pack-112ea9a83fa76468c74ce0f7b4703fe0ad289540.pack] => Array
                        (
                            [expected] => 
                            [current] => 3cb51aac6888926a2917c484b8b79a0193f781baf5570faec9a73127f0687ff0a4ecb9352f35448a84afc09cfe860742f7a09d727a45a7bf10a9aa8396b6fe89
                        )

                    [.git/objects/pack/pack-112ea9a83fa76468c74ce0f7b4703fe0ad289540.idx] => Array
                        (
                            [expected] => 
                            [current] => ee54c5d7173e2ea15b83f1fc2b3a70867cdb4a3c1f1bf1fc3c6867ba05063bdd5530af7f967b0e278266339f174d2bc5e426b113a3416afb295098e0d5840c43
                        )

                    [.git/info/exclude] => Array
                        (
                            [expected] => 
                            [current] => 9828c6ecdf91bf117416e17f4ee9caee2e1e37b6fb00b9ff04035ace17a3089b9d0a25c6baa1046c0e1c62d3da88838e8fca74ea82973d6b975905fde58f3072
                        )

                    [.git/HEAD] => Array
                        (
                            [expected] => 
                            [current] => 0ae4adc954e969e3961dd8ae0b159c0249d192ae6e21f0de3c9db808d23d4592a39e3066744fdcd977140ac0ade0344d0973d574e2f0d88d6e626f9aeef6f9d5
                        )

                    [.git/description] => Array
                        (
                            [expected] => 
                            [current] => f7e152f75b124c3e1c5d12f00427729d9eec4e2c1bf70d7606440a6600d003367eb178331e75ab976a61496e79c2c822020849d28ffd170946397b934611b471
                        )

                    [.git/hooks/commit-msg.sample] => Array
                        (
                            [expected] => 
                            [current] => d6bb7fa747f4625adf1877f546565cbe812ca7dd4168f7e9068e6732555d8737eba549546cf5946649e3f38de82d173aaf9c160a4c9f9445655258b4c5f955eb
                        )

                    [.git/hooks/applypatch-msg.sample] => Array
                        (
                            [expected] => 
                            [current] => a31e790b1762b64fd2cca171455a054e9b52180481b15cc9c213e69edef960d1d9f296151068014fa12fafbec4ef8da838f1c3c76c79966a71405401f10b2a83
                        )

                    [.git/hooks/pre-push.sample] => Array
                        (
                            [expected] => 
                            [current] => d5d455f08cb49616408df156734066dfb6776bdbe480e10fcc27f2d8aa20984e2022ae4ccdd51c2c52f07c40368b9de14a44d491d4d7a9701b71a1a5a3d47e8d
                        )

                    [.git/hooks/prepare-commit-msg.sample] => Array
                        (
                            [expected] => 
                            [current] => fbf15f12136a413dd590e57392e6122714d67456beed50d9ef285e40076a138a7d44291b5642fe5c518dc56c640436caf6225d1a966e06c042b30e6a7d08dcef
                        )

                    [.git/hooks/post-update.sample] => Array
                        (
                            [expected] => 
                            [current] => 473ad124642571656276bf83b9ff63ab1804d3c23a5bdae52391c6f70a894849ac60c10c9d31deff3938922ce83b68b1e60c11592bbf7ea503f4acd39968cefa
                        )

                    [.git/hooks/pre-rebase.sample] => Array
                        (
                            [expected] => 
                            [current] => bad3f48e56d7497bc2b04b2405195c067cb958c77b96583ae32921a2f0439b9b506d9c4d6ac2465ab46a6d2df0c6c1491308eced3a569320957d22491f40a7be
                        )

                    [.git/hooks/pre-commit.sample] => Array
                        (
                            [expected] => 
                            [current] => 4a7ac2ed2ffe50d2a997c3477b5855c3d19423c295a82f7d660be3418217a183b0ce25f94ae2e350f4d93eda3b75a4bd62cf27f0685d8a837919bcc9e7e0962a
                        )

                    [.git/hooks/pre-applypatch.sample] => Array
                        (
                            [expected] => 
                            [current] => 89fb811a9152509a01d4a156212e7ede5e957157e59e308176e08afa6c28fa88e23bbf1dc2989528628feed641456237c9e6d66ac73b74a56ab426f953cb25dc
                        )

                    [.git/hooks/update.sample] => Array
                        (
                            [expected] => 
                            [current] => f8e20df0e6c970fa809d5c9494cb9d5e32894fe20f23f6730df84f5fa065e52c55cca98d0db1ed17df53c606629c787ae56b6af6faca527f62c817f8cb148c1a
                        )

                    [.git/config] => Array
                        (
                            [expected] => 
                            [current] => 09ba69d75e572960c4574bf578ab882f1bb0f50d7040f2f8295b6c7bbc43af1f9656151de184769408c20d4873ae4eae505e6512cf619994ed30b6059d1d332f
                        )

                    [.git/index] => Array
                        (
                            [expected] => 
                            [current] => a8ac4c87fe038badbc6cd366bce69fa8238c6b26edd41484869e449ed32b144f9c14d4c4ce1a451d1f4d631c11f61fe0260b0ecb5910ad65e1f283e26328a0d7
                        )

                    [.git/refs/heads/develop] => Array
                        (
                            [expected] => 
                            [current] => 6807add88a7dbb8250337a407e313ad2ccf73dfbbc85ed26e06d6fb0a2624260d0215574c33fefe369f3e388091a9cf6346380c36ac70302bddcda591c6d27e6
                        )

                    [.git/refs/remotes/origin/HEAD] => Array
                        (
                            [expected] => 
                            [current] => 478213bbd19d42b6cb00b888c4c64ba85586cd820d7f0148b6039f6a184da9e157af397ebc5af4b62141e3f9468b3b680cbadcdb5e3a5a8af3c8b05f26070d16
                        )

                    [.git/logs/HEAD] => Array
                        (
                            [expected] => 
                            [current] => c1ed69e0b7ec54ca94b3a55bc0753e773bd18778a3afb8544bc29cdd02900a027e3a474ae3858e1f2357a2cd4cbd982cf3466ee81d5b1817d49a6a91cc382524
                        )

                    [.git/packed-refs] => Array
                        (
                            [expected] => 
                            [current] => 68128c3f7b5c740c81a8452b74b75a49b178de3c968e2138f00fcfd0b146f4429bab1393ca9d4c58f188f08d8ff280e87f635f8916f3afc9755ee1b838cbe14a
                        )

                )

        )

)

**Comment by pbek** [comment]
Did you checkout from git (I can see a .git folder) or use the release (like you are supposed to)?

**Comment by pbek** [comment]
https://github.com/pbek/ownbackup/releases

**Comment by JSoko** [comment]
Had the issue after updating from NC 11.0.1RC1 to NC 11.0.1 with the updater.
```
Results
=======
- ownbackup
	- INVALID_HASH
		- README.md
		- appinfo/info.xml
```

Removed the app manualy from the app folder and installed it again from the Nexcloud Apps-Page.
=> No further Problem with the check...

### Server configuration
**Operating system**: Linux OdOc 3.10.96 #1 SMP PREEMPT Mon May 23 01:50:06 BRT 2016 armv7l

**Web server:**  apache2handler

**Database:** mysql

**PHP version:** 7.0.13-0ubuntu0.16.04.1

**Nextcloud version:** 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from NC 11.0.1RC1 to NC 11.0.1 with the Updater

**List of activated apps:**
<details>
	<summary>App list</summary>

	```
	Enabled:
	 - activity: 2.4.1
	 - admin_audit: 1.1.0
	 - bookmarks: 0.9.1
	 - calendar: 1.4.1
	 - comments: 1.1.0
	 - contacts: 1.5.2
	 - dav: 1.1.1
	 - direct_menu: 0.10.0
	 - federatedfilesharing: 1.1.1
	 - files: 1.6.1
	 - files_automatedtagging: 1.1.1
	 - files_downloadactivity: 1.0.0
	 - files_pdfviewer: 1.0.1
	 - files_sharing: 1.1.1
	 - files_texteditor: 2.2
	 - files_trashbin: 1.1.0
	 - files_versions: 1.4.0
	 - files_videoplayer: 1.0.0
	 - flowupload: 0.4
	 - html5_videoplayer: 1.0
	 - issuetemplate: 0.0.1
	 - keeweb: 0.3.0
	 - logreader: 2.0.0
	 - lookup_server_connector: 1.0.0
	 - news: 10.1.0
	 - nextcloud_announcements: 1.0
	 - nextnotes: 0.9.1
	 - notes: 2.2.0
	 - notifications: 1.0.1
	 - ocsms: 1.11.4
	 - ownbackup: 16.11.0
	 - password_policy: 1.1.0
	 - provisioning_api: 1.1.0
	 - serverinfo: 1.1.1
	 - sharebymail: 1.0.1
	 - shorten: 0.0.15
	 - spreed: 1.1.2
	 - spreedme: 0.3.5
	 - survey_client: 0.1.5
	 - systemtags: 1.1.3
	 - tasks: 0.9.4
	 - templateeditor: 0.2
	 - theming: 1.1.1
	 - twofactor_backupcodes: 1.0.0
	 - updatenotification: 1.1.1
	 - workflowengine: 1.1.1

	Disabled:
	 - encryption
	 - external
	 - federation
	 - files_accesscontrol
	 - files_external
	 - files_retention
	 - firstrunwizard
	 - flowupload.old
	 - gallery
	 - qownnotesapi
	 - user_external
	 - user_ldap
	 - user_saml
	```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/cloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "integrity.check.disabled": false,
    "dbname": "owncloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***t",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.1und1.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox 50.1.0
**Operating system:**
Windows 10 Pro

**Comment by pbek** [comment]
Great, so can we close this issue?

**Comment by gjelsas** [comment]
For me the problem persists, with the app from the store , and the app from the release page.

Raw output
==========
Array
(
    [ownbackup] => Array
        (
            [INVALID_HASH] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
                            [current] => 19292ca3fd349cb446ad6f374ab62b4b9e0f8f69c863460e53a36271c14f59fa64bc783979edbf084b423c44c3fd3860e09814320ad7f2ab6558e4b9b459bf0f
                        )

                    [appinfo/info.xml] => Array
                        (
                            [expected] => 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
                            [current] => 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add
                        )

                )

        )

)



System: Debian 8 
Version: NC 11.0.1

**Comment by JSoko** [comment]
@gjelsas did You remove the app manualy and installed it again from the NC-Store?

p.e.:
`rm /var/www/nextclooud/apps/ownbackup -r`

**Comment by gjelsas** [comment]
I tried deleting it from cli and from the appspage. I installed it from the NC/appspage, by downloading it from the releases page, also via "git clone". Always the issue with the signatures...

Am 17. Januar 2017 08:43:15 MEZ schrieb Joachim Sokolowski <notifications@github.com>:

**Comment by pbek** [comment]
If you installed it via your apps page on your NC 11 server it shouldn't even be possible to fail the integrity check, because the release needs to be signed by NC (not oC) while putting it into the NC store...

**Comment by gjelsas** [comment]
Still it complains! Is there a signaturestore somewhere, like in the mysql Database or on the filesystem? Did I mess up my installation maybe?

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- ownbackup
	- INVALID_HASH
		- README.md
		- appinfo/info.xml

Raw output
==========
Array
(
     [ownbackup] => Array
         (
             [INVALID_HASH] => Array
                 (
                     [README.md] => Array
                         (
                             [expected] => 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
                             [current] => 19292ca3fd349cb446ad6f374ab62b4b9e0f8f69c863460e53a36271c14f59fa64bc783979edbf084b423c44c3fd3860e09814320ad7f2ab6558e4b9b459bf0f
                         )

                     [appinfo/info.xml] => Array
                         (
                             [expected] => 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
                             [current] => 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add
                         )

                 )

         )

)


Am 17.01.2017 um 12:08 schrieb Patrizio Bekerle:

**Comment by rcmcronny** [comment]
I have the exact same issue. After upgrade of NC , hash error. Disabled the app, then removed the app from the app dir and re installed it. Now i have 2 files with a hash mismatch like the post before me.

**Comment by FriedCircuits** [comment]
I have the same issue with readme and info files. I used the command line nextcloud updater.

**Comment by pbek** [comment]
I checked out the master branch of ownbackup and got no error with `php occ integrity:check-app ownbackup` on NC 11 and 12.

**Comment by pbek** [comment]
Did you try to install it directly from your NC apps page on your server?

**Comment by JSoko** [comment]
Did you rerun the integrycheck after removing ownbackup from the /apps folder?

**Comment by gjelsas** [comment]
Yes, always! 

Am 18. Januar 2017 08:22:10 MEZ schrieb Joachim Sokolowski <notifications@github.com>:

**Comment by rcmcronny** [comment]
I have tried it with the last release from this repo and there is also an issue (same hash issues and missing file .editorconfig error), if it works with master, perhaps you should release it as new version ?

**Comment by FriedCircuits** [comment]
Nothing seems to work. Either cloning the whole repo or downloading specific files from either branch. I noticed that calendar app issued and update that fixed the same issue with it. Now I also have the missing file error.

**Comment by Franzz** [comment]
I had the same issue. fixed it by reapplying ownership on the folder
`chown -R www-data:www-data ownbackup/`

**Comment by FriedCircuits** [comment]
I just fixed it a few minutes ago. Long story short I deleted the app and let Nextcloud re-download it. I thought I had done that already though.

**Comment by pbek** [comment]
Great!

**Comment by rcmcronny** [comment]
for me to. i tried that also, so i tried again and works.
Deactivated app, deleted app folder, refreshed the Integrity check, then go to app store and reactivate the app again, it will be redownloaded and all fine.

**Comment by nursoda** [comment]
Also had this issue. Thought it would be a glitch to be fixed in next NC version. The important part is to RERUN the integrity check (2nd link in the warning) while the app is deactivated and REMOVED.

Yet, there's something I don't get: If ownbackup packages are signed, how come that I got wrong files or sigs? I never fiddled with ownbackup! Just upgraded to 11.0.1 beta and to release a couple of days later.

**Comment by nursoda** [comment]
I just upgraded two NC instancees and I do experience the exact same issue AGAIN. The first instance was upgraded from 10.0.2 RC3 to 10.0.2 (release), the other from from 10.0.1 (release) to 10.0.2 (release). Both instances showed the behavior from first post before "repairing" them as proposed in this thread. So it seems there IS an underlying issue that is NOT FIXED (but suppressed) by the fix.

**Comment by rcmcronny** [comment]
same for me, updated from 11.0.1 to 11.0.2 and happend the same. disabled the plugin, remove directory, refresh checksums and install it again worked again.

**Comment by mr-bolle** [comment]
I have also an error [INVALID_HASH] after upgrading from Nextcloud 11.0.1 to 11.0.2, before i don't have any Issue with integrity of this Plugin. I could not find a solution yet.

Apache2 Server with PHP 7.0.15-1

1. i try to install from [nextcloud.com](https://apps.nextcloud.com/apps/ownbackup)

> Results
>- ownbackup
> 	- INVALID_HASH
> 		- README.md
> 		- appinfo/info.xml
> Raw output
> ==========
> Array
> (
>     [ownbackup] => Array
>         (
>             [INVALID_HASH] => Array
>                 (
>                     [README.md] => Array
>                         (
>                             [expected] => 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
>                             [current] => 19292ca3fd349cb446ad6f374ab62b4b9e0f8f69c863460e53a36271c14f59fa64bc783979edbf084b423c44c3fd3860e09814320ad7f2ab6558e4b9b459bf0f
>                         )
> 
>                     [appinfo/info.xml] => Array
>                         (
>                             [expected] => 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
>                             [current] => 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add
>                         )
> 
>                 )
> 
>         )
> 
> )
> 

2. Diable plugin, remove directory, rescan, and install the plugin with *git clone https://github.com/pbek/ownbackup.git apps/ownbackup* and rescan again. with follow Restult.

*sudo -u www-data php occ integrity:check-app ownbackup*

>   - FILE_MISSING:
>     - .editorconfig:
>       - expected: 3f6603e83dd948fb07946fd9fee11673c1196a3e3710a6b5dfd2f8861a3cfd49a8abca1273f9678f529d0c2edca9fd3f6d51adc07bcd071f9aa0716075f7e048
>       - current: 
>   - INVALID_HASH:
>     - README.md:
>       - expected: 04ad0a9e5212c8db98fd11696e853f3f52dd9d7bee52dd2362c3303e032875b6c9fd6a2aa5151468de99ede5e1afa527349fb81efa872b977d902040e0a3fac6
>       - current: ece1addb7b7eda683984d18641b06a7c19e464954859b32fced97d2b5006b9a7bc3e2bdaa57194a635155ba0104750eb7f495a383a0bdcc609a00147cc5cb6f5
>     - appinfo/info.xml:
>       - expected: 5b6b9f1498bff49f35122a9fbe07451d0643ff35adc049c46ac1928dd005afd1de0d6d0106179dff5da2f4f85200df7cb04088d8faab97e34bfe0c265385f7a9
>       - current: 0f0e4160fbd178b899c0da06ab56f548f1af17f07d5581badabfb93a06a37f257c1b3dbff2c608b0fe02fb285285fff6ebf7f5d8a3179426608f222a074b4add

**Comment by pbek** [comment]
I now made a new release, can you please try it: <https://github.com/pbek/ownbackup/releases/tag/17.3.0>
I didn't get any integrity check errors on NC 11.0.2.

**Comment by nursoda** [comment]
Should I download and install from the link or is it visible in the NC app store?

**Comment by pbek** [comment]
I installed it from the NC store.

**Comment by mr-bolle** [comment]
Hi pbek, thank you very much. I update this app, and rescan the integrity. And the check don't show me any errors.

**Comment by pbek** [comment]
Then the 1.5 hours to make a new release and publish it in all stores were well spent... Thank you for testing.

**Comment by nursoda** [comment]
I'm not sure if updating the APP and not getting an error is sufficient to test. For me, if my NC installation was in a "no error" state, (re)installing ownBackup never yielded an error. Only upgrading the NC INSTALLATION itself did. We'll see on the next NC update. If I get an error then, I'll post here. If not, I'll try to remember and post here anyway. THANKS for all your efforts!!

**Comment by pbek** [comment]
You can always check the integrity of the app with `php occ app:check-code ownbackup`.

**Comment by nursoda** [comment]
`sudo -u www-data php occ app:check-code ownbackup`
yields
`App is compliant - awesome job!`

**Comment by pbek** [comment]
sorry, I meant: `php occ integrity:check-app ownbackup`

**Comment by nursoda** [comment]
`sudo -u www-data php occ integrity:check-app ownbackup`
yields
` `
(nothing, just a new prompt line)

That is using 17.3 - unfortunately I had already "fixed" all my instances, so I can only test after another NC update.

**Comment by pbek** [comment]
> (nothing, just a new prompt line)

yes, that means it was a success

**Comment by nursoda** [comment]
After upgrading 11.0.3 to 12.0 beta 2 and ownbackup to 17.3, I see this
```
# sudo -u www-data php occ integrity:check-app ownbackup
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Certificate is not valid.
```
I solved it by deactivating and uninstalling the app, then re-scanning integrity, then re-installing the app.

**Comment by nursoda** [comment]
It may be of importance that I use redis-server to speed up the website. Does that make any difference? It's still the same on each upgrade (within NC12 betas or coming from 11.0.3 to 12b4: I always get the integrity failed with the report as attached.
[ownbackup-integrity-failed-nc12b4.txt](https://github.com/pbek/ownbackup/files/1013796/ownbackup-integrity-failed-nc12b4.txt)

**Comment by pbek** [comment]
Redis should make no difference.
The integrity check in NC 12 is a bit of a pain in the bum (because of the ownCloud split)...
I've still open questions at <https://github.com/nextcloud/server/issues/4852>.

**Comment by nursoda** [comment]
If I DELETE ownbackup first, then do the NC update, then install the app, I do NOT get any warning.
So signature seems to be fine!? Otherwise it should not install, should it?

**Comment by pbek** [comment]
I don't know why you don't get the error. The problem is that the app (in addition to being correctly signed for the NC app store) is signed with an ownCloud certificate and in NC 12 that yields an error...
