### ISSUE TITLE
Causes malfunction in "Group Folders" and admin log

### ISSUE THREAD

**Issue by jeffrson** [pbek/ownbackup#48]
After downloading and installing nextbackup the admin page of [Group Folders](https://github.com/nextcloud/groupfolders) as well as the administration logging page stay blank.

Disabling nextbackup restores these pages.

App version: 20.9.0
Nextcloud version: 20.0.5

**Comment by pbek** [comment]
Any errors in the browser's web console?

**Comment by jeffrson** [comment]
Well, there was no obvious one. However, now that I know I need to enable/disable nextbackup, here's a message that only appears, when the bug occurs:
![image](https://user-images.githubusercontent.com/9551280/104808466-cd191600-57e6-11eb-8c6a-092ccae6f714.png)

**Comment by pbek** [comment]
I guess *tipsy* isn't added by Nextcloud itself any more, I just removed the call. The *Group folders* admin screen now works for me.

## 21.1.0
- fixed a problem where *Group folders* app admin screen wasn't shown if *Nextbackup* was also installed

There now is a new release in the Nextcloud app store, could you please test it and report if it works for you?

**Comment by jeffrson** [comment]
New release is not yet available for me - I'll update this comment as soon as I see the new version.

BTW, for admin logging page there's the same error message, so this would be probably solved as well.

Thanks so far!

**Comment by pbek** [comment]
I can see it on https://apps.nextcloud.com/apps/nextbackup, I guess you'll get it soon. 😉

**Comment by jeffrson** [comment]
Hmmm - still not availble. But I'm patient...

However, I want to add two findings:

1) This bug was also responsible for password rules (in Security) not being saved.
2) Installing the [Impersonate](https://github.com/nextcloud/impersonate) app "magically" fixes the problem. Strange. The bug returns if "Impersonate" is disabled.

**Comment by pbek** [comment]
Strange. I already updated my server an hour ago.

**Comment by jeffrson** [comment]
Okay - meanwhile it arrived and fixed the bug. Thank you for the quick solution!!!

**Comment by pbek** [comment]
Great, thank you for reporting and testing!

**Comment by maiolif** [comment]
> ## 21.1.0
> 
>     * fixed a problem where _Group folders_ app admin screen wasn't shown if _Nextbackup_ was also installed
> 


Tested. It's working also for me. New version of nextbackup allow to show admin screen in group folder app.
THANKS A LOT

**Comment by pbek** [comment]
I'm glad it works 😁
